version: 4.4.0.{build}
configuration: Release
platform: x64
build:
  project: LDView.vcxproj
  verbosity: minimal

cache:
  - Build
  - LDLib/.obj-qt5
  - TRE/.obj-qt5
  - LDLoader/.obj-qt5
  - TCFoundation/.obj-qt5
  - LDExporter/.obj-qt5
  - QT/.obj-qt5
  
environment:
  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      TOOLSET: v140
#      SDK: 8.1
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      TOOLSET: v141
#      SDK: 8.1
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#      TOOLSET: v142
#      SDK: 10.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      TOOLSET: v143
      SDK: 10.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      QT: 5.15
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
      QT: 6.5
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
#      QT: 6.9.1
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma

install:
- sh: if [ `uname -s` = Linux ] ; then sudo apt-get update -qq || true ; fi
- sh: if [ `uname -s` = Linux ] ; then sudo apt-get install -y -qq --no-install-recommends libpng-dev libjpeg-dev libtinyxml-dev libgl2ps-dev libgl1-mesa-dev libglu1-mesa-dev libminizip-dev ; fi
- sh: if [ `uname -s` = Linux ] ; then if [ -z "$QT" ] ; then sudo apt-get install -y -qq --no-install-recommends qtbase5-dev qt5-qmake qttools5-dev-tools libqt5opengl5-dev cmake libosmesa6-dev build-essential debhelper lintian fakeroot extra-cmake-modules libkf5kio-dev libkf5kdelibs4support5-bin ; fi ; fi

build_script:
- sh: if [ `uname -s` = Linux ] ; then cd QT; if [ -n "$QT" ] ; then $HOME/Qt/$QT/gcc_64/bin/qmake -spec linux-g++-64 ; make ; else ./makedeb -qt5 ; fi ; fi
- sh: if [ `uname -s` = Darwin ] ; then cd MacOSX/LDView ; xcodebuild ; fi
- cmd: msbuild "C:\projects\ldview\LDView.sln" /verbosity:minimal /p:PlatformToolset=%TOOLSET% /p:WindowsTargetPlatformVersion=%SDK% /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild "C:\projects\ldview\LDView.sln" /verbosity:minimal /p:PlatformToolset=%TOOLSET% /p:WindowsTargetPlatformVersion=%SDK% /p:Configuration=Release /p:Platform=win32 /t:Launcher /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild "C:\projects\ldview\LDViewThumbs\LDViewThumbs.vcxproj" /verbosity:minimal /p:PlatformToolset=%TOOLSET% /p:WindowsTargetPlatformVersion=%SDK% /p:Configuration=Release /p:SolutionDir=C:\projects\ldview\ /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: msbuild "C:\projects\ldview\LDViewThumbs\LDViewThumbs.vcxproj" /verbosity:minimal /p:PlatformToolset=%TOOLSET% /p:WindowsTargetPlatformVersion=%SDK% /p:Configuration=Release /p:SolutionDir=C:\projects\ldview\ /p:Platform=win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#- cmd: if exist "\Program Files (x86)\Inno Setup 6\iscc.exe" "\Program Files (x86)\Inno Setup 6\iscc.exe" C:\projects\ldview\LDView64.iss



